name: probe Action

on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    name: probe Action
    #if: contains(github.event.issue.labels.*.name, 'test-action')

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.6.1'
          
      - name: Install json-to-env
        run: npm install -g json-to-env


      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/app_request.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > bug-details.json
      
      - run: echo '${{ steps.issue-parser.outputs.issueparser_Name }}' > name.json

      - name: Show parsed data
        run: |
          FRAME=$(curl https://win11react-api-united-states.herokuapp.com/api/x-frame?url=${{ steps.issue-parser.outputs.issueparser_URL }})
          echo $FRAME
      
      - uses: ben-z/actions-comment-on-issue@1.0.2
        if: $FRAME==true
        with:
          message: "Sorry the URL for the website ${{ steps.issue-parser.outputs.issueparser_Name }} is not iframeable."
          GITHUB_TOKEN: ${{ secrets.BOT }}
          
      - uses: ben-z/actions-comment-on-issue@1.0.2
        if: $FRAME==false
        with:
          message: "Thankyou for suggesting, ${{ steps.issue-parser.outputs.issueparser_Name }} once approved it will be added. "
          GITHUB_TOKEN: ${{ secrets.BOT }}       
