name: probe Action

on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    name: probe Action
    #if: contains(github.event.issue.labels.*.name, 'test-action')

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.6.1'
          
      - name: Install json-to-env
        run: npm install -g json-to-env


      - name: Run Action
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '>>'

      - name: Show parsed data
        run: |
          echo '${{ steps.parse.outputs.payload }}' > data.json
          json-to-env data.json $HOME/.bashrc
          source ~/.bashrc
          printenv Name
