name: probe Action

on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    name: probe Action
    #if: contains(github.event.issue.labels.*.name, 'test-action')

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/app_request.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > bug-details.json
      
      - run: echo '${{ steps.issue-parser.outputs.issueparser_Name }}' > name.json

      - name: API
        run: |
          echo '::set-output name=API::$(curl https://win11react-api-united-states.herokuapp.com/api/x-frame?url=${{ steps.issue-parser.outputs.issueparser_URL }})'
          echo done
          
      - name: iframe
        run: echo ${{ steps.API.outputs.API }}
      
      - uses: ben-z/actions-comment-on-issue@1.0.2
        if: ${{ steps.API.outputs.API == 'true' }}
        with:
          message: "Sorry the URL for the website ${{ steps.issue-parser.outputs.issueparser_Name }} is not iframeable."
          GITHUB_TOKEN: ${{ secrets.BOT }}
          
      - uses: ben-z/actions-comment-on-issue@1.0.2
        if: ${{ steps.API.outputs.API == 'false' }}
        with:
          message: "Thankyou for suggesting, ${{ steps.issue-parser.outputs.issueparser_Name }} once approved it will be added. "
          GITHUB_TOKEN: ${{ secrets.BOT }}       
